apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: crkcwdt55-nodejs
  janus-idp.io/tekton: crkcwdt55-nodejs
  backstage.io/kubernetes-id: crkcwdt55-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: crkcwdt55-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
